apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-chart.fullname" . }}
  labels:
    {{- include "test-chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
